apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredRouteName
metadata:
  name: required-route-name
spec:
  enforcementAction: deny       
  match:
    namespaces:
      - "petclinic-bluegreen-user0"  
      - "petclinic-beta-user0"    
    kinds:
      - apiGroups: ["*"]
        kinds: ["Route"]
  parameters:
    name: route-petclinic-bluegreen 
