apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: template-constraint-requiredlabel-${USER}
objects:
- apiVersion: constraints.gatekeeper.sh/v1beta1
  kind: RequiredLabels
  metadata:
    name: required-label-${USER}
  spec:
    enforcementAction: deny
    match:
      namespaces:
        - "petclinic-bluegreen-${USER}"
      kinds:
        - apiGroups: ["*"]
          kinds: ["Deployment"]
        - apiGroups: ["*"]
          kinds: ["Service"]
        - apiGroups: ["*"]
          kinds: ["Route"]          
    parameters:
      labels: ["app"]
parameters:
- name: USER
  description: "Username"
  required: true
  value: ${USER}
