apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: livemigrate-template
objects:
- apiVersion: constraints.gatekeeper.sh/v1beta1
  kind: ContainerRatio
  metadata:
    name: container-ratio
  spec:
    enforcementAction: deny
    match:
      namespaces:
        - "petclinic-bluegreen-${USER}"
      kinds:
        - apiGroups: [""]
          kinds: ["Pod"]
    parameters:
      ratio: "3"
parameters:
- name: USER
  description: "Username"
  required: true
  value: ${USER}
