apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerRatio
metadata:
  name: container-ratio
spec:
  match:
    namespaces:
      - "petclinic-bluegreen-user0"
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    ratio: "3"
