apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ContainerRatio
metadata:
  name: container-ratio
spec:
  match:
    namespaces:
      - "petclinic-bluegreen"      
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    cpu: "200m"
    memory: "1Gi"
