apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabelsSvc
metadata:
  name: required-label-service
spec:
  enforcementAction: dryrun       
  match:
    namespaces:
      - "petclinic-bluegreen"      
    kinds:
      - apiGroups: ["*"]
        kinds: ["Service"]
  parameters:
    labels: ["app"]
