apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: livemigrate-template
objects:
- apiVersion: constraints.gatekeeper.sh/v1beta1
  kind: RequiredLabelsRoute
  metadata:
    name: required-label-route
  spec:
    enforcementAction: deny
    match:
      namespaces:
        - "petclinic-bluegreen-${USER}"
      kinds:
        - apiGroups: ["*"]
          kinds: ["Route"]
    parameters:
      labels: ["app"]
parameters:
- name: USER
  description: "Username"
  required: true
  value: ${USER}
