apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabelsRoute
metadata:
  name: required-label-route
spec:
  enforcementAction: deny     
  match:
    namespaces:
      - "petclinic-bluegreen"      
    kinds:
      - apiGroups: ["*"]
        kinds: ["Route"]
  parameters:
    labels: ["app"]
