apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: template-requiredlabelsdeployment-${USER}
objects:
- apiVersion: templates.gatekeeper.sh/v1beta1
  kind: ConstraintTemplate
  metadata:
    name: requiredlabelsdeployment${USER}
  spec:
    crd:
      spec:
        names:
          kind: RequiredLabelsDeployment${USER}
        validation:
          # Schema for the `parameters` field
          openAPIV3Schema:
            properties:
              labels:
                type: array
                items: string
    targets:
      - target: admission.k8s.gatekeeper.sh
        rego: |
          package requiredlabelsdeployment${USER}
          violation[{"msg": msg, "details": {"missing_labels": missing}}] {
            provided := {label | input.review.object.metadata.labels[label]}
            required := {label | label := input.parameters.labels[_]}
            missing := required - provided
            count(missing) > 0
            msg := sprintf("You must provide labels: %v", [missing])
          }
parameters:
- name: USER
  description: "Username"
  required: true
  value: ${USER}          
