apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: template-constraint-requiredresourcequota-${USER}
objects:
- apiVersion: constraints.gatekeeper.sh/v1beta1
  kind: RequiredResourceQuota
  metadata:
    name: requiredresourcequota${USER}
  spec:
    enforcementAction: deny      
    match:
      namespaces:
        - "petclinic-bluegreen-${USER}"
        - "petclinic-test-${USER}"      
      kinds:
        - apiGroups: ["*"]
          kinds: ["Deployment"]
parameters:
- name: USER
  description: "Username"
  required: true
  value: ${USER}
