apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ResourceQuota
metadata:
  name: resourcequota
spec:
  enforcementAction: deny
  match:
    namespaces:
      - "petclinic-bluegreen-user0"  
    kinds:
      - apiGroups: ["*"]
        kinds: ["Deployment"] 
