apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "openshift-gatekeeper-system"
spec:
  match:
    - excludedNamespaces: ["petclinic-beta-user0"]
      processes: ["webhook"]          
  sync:
    syncOnly:
      - group: ""
        version: "*"
        kind: "Namespace" 
