kind: ConfigMap
apiVersion: v1
metadata:
  name: user-config
  namespace: ${USER_NS}-terminal
data:
  env: |-
    OCP_CONSOLE=https://console-openshift-console.apps.cluster-4a3f.sandbox453.opentlc.com
    OCP_API=https://api.cluster-4a3f.sandbox453.opentlc.com:6443
    USER=user3
    PASSWORD=redhat
    APPS_NS=deploy-app
    LABS_HOME=lab-gatekeeper
    APPS_CLUSTER=cluster-4a3f.sandbox453
          
