kind: ConfigMap
apiVersion: v1
metadata:
  name: user-config
  namespace: ${USER}-terminal
data:
  env: |-
    OCP_CONSOLE=https://console-openshift-console.apps.cluster-faf8.sandbox1234.opentlc.com
    OCP_API=https://api.cluster-faf8.sandbox1234.opentlc.com:6443
    USERNAME=${USERNAME}
    USER=${USER}
    PASSWORD=${PASSWORD}
    APPS_NS=deploy-app
    LABS_HOME=/home/user/lab-gatekeeper
    APPS_CLUSTER=cluster-faf8.sandbox1234
          
