= Lab 2 - Required labels
:author: Coral Romero
:email: cromerob@redhat.com
:imagesdir: ./images
:toc: left
:toc-title: Required labels

[Abstract]

In this second lab we are going to verify that every service, route and deployment match the same labels as part of the deployment process.
As we are testing different kinds of resources like Deployment, Route and Service, we are going to deploy different constraints. 
Furthermore we are going to exclude a namespace to see how to implement this functionality.

:numbered:
== Deploy constraint

=== Deploy Constraint Template

First we need to deploy the constraint templates where we are going to check the existing labels of the object under test and use the substraction operator to check any missing label.

----
oc apply -f lab-gatekeeper-files/lab2/constraintTemplateDeployment.yaml
oc apply -f lab-gatekeeper-files/lab2/constraintTemplateRoute.yaml
oc apply -f lab-gatekeeper-files/lab2/constraintTemplateSvc.yaml
----

== Deploy Constraint 

Additionally we need to deploy the constraints where we are going to limite the impact to "petclinic-bluegreen" namespace and specify the required label.

For this example parameters are:

- Namaspace where the rule is implemented: petclinic-bluegreen.
- Resource under test: Deployment, Service and Route.
- Required label: "app".
- Enforcement action: dryrun. Dryrun means you will be alerted if your resources violate any constraint but you will be allowed to create the resource.

----
oc apply -f lab-gatekeeper-files/lab2/constraint-deployment.yaml
oc apply -f lab-gatekeeper-files/lab2/constraint-route.yaml
oc apply -f lab-gatekeeper-files/lab2/constraint-service.yaml
----

== Test constraint

=== Test negative case

For testing the positive case we are going to deploy these resources to the allowed namespace "petclinic-bluegreen" and to the excluded namespace "petclinic-beta-username".
You should expect these resources to be deployed properly because they accomplish the constraints.

----
oc apply -f lab-gatekeeper-files/lab2/deploy-app-blue.yaml -n petclinic-bluegreen-$username
oc apply -f lab-gatekeeper-files/lab2/deploy-app-blue.yaml -n petclinic-beta-$username
----

=== Test positive case

For testing the negative case we are going to deploy a set of non-compliance resources to the namespaces.

For the first namespace you should be prompted with error message "" as they don't have the required labels.
For the second namespace as it's excluded from the constraint you should be able to create the resources.

----
oc apply -f lab-gatekeeper-files/lab2/deploy-app-blue-negative.yaml -n petclinic-bluegreen-$username
oc apply -f lab-gatekeeper-files/lab2/deploy-app-blue-negative.yaml -n petclinic-beta-$username
----

== Dryrun

The recently deployed constraints were created as in the first lab with enforcement mode to "deny" however gatekeeper other mode called "dryrun" which enables constraints to be deployed without enforcing them. This means that non compliance resources will be created but violations will be audited.

If we patch the existing constraints to change the enforcement mode to "dryrun" and the try to redeploy the resources we should be able to create all of them but violations will be registered on the status section.

----
oc patch requiredlabelsdeployment.constraints.gatekeeper.sh/required-label-deployment -p '{"spec":{"enforcementAction":"dryrun"}}' --type merge
oc patch requiredlabelssvc.constraints.gatekeeper.sh/required-label-service  -p '{"spec":{"enforcementAction":"dryrun"}}' --type merge
oc patch requiredlabelsroute.constraints.gatekeeper.sh/required-label-route -p '{"spec":{"enforcementAction":"dryrun"}}' --type merge
----

Then check the status of the violated constraints:

WARNING: You may need to wait the audit interval time till status is updated.

----
oc get requiredlabelsdeployment.constraints.gatekeeper.sh/required-label-deployment -o yaml
oc get requiredlabelssvc.constraints.gatekeeper.sh/required-label-service -o yaml
oc get requiredlabelsroute.constraints.gatekeeper.sh/required-label-route -o yaml
----
