= Lab 3 - Required route names
:author: Coral Romero
:email: cromerob@redhat.com
:imagesdir: ./images
:toc: left
:toc-title: Required route name

[Abstract]

In this use case we are going to verify that the route name follows the required pattern to validate it.

For this example we are going to apply this constraint over two different projects, "petclinic-bluegreen" which is the production environment and "petclinic-beta-user0" which is the development environment. 

Previously we are going to create a Config resource to exclude "webhook" process from "petclinic-beta-user0" project so we will be able to create non valid resources but those violations will be registered on the status.

:numbered:
== Deploy constraint

=== Deploy Config

As mentioned we need to create a config resource to exclude some processes from a namespace, "webhook" for "petclinic-beta-user0". This is a cluster wide resource which should be created by an user with cluster-admin privileges so you can check the existing resource with this command:

----
oc get config.config.gatekeeper.sh/config -o yaml -n openshift-gatekeeper-system
----

=== Deploy Constraint Template

First we need to deploy the constraint templates where we are going to check the existing name of the object under test.

----
oc apply -f lab-gatekeeper-files/lab3/constraintTemplate.yaml
----

=== Deploy Constraint 

Additionally we need to deploy the constraints where we are going to limite the inpact to "petclinic-bluegreen" and "petclinic-beta-user0"  namespace and specify the required name.

For this example parameters are:

- Namaspace where the rule is implemented: petclinic-bluegreen and petclinic-beta-user0.
- Resource under test: Route.
- Required name: "quarkus-petclinic-bluegreen".
- Enforcement action: deny.

----
oc apply -f lab-gatekeeper-files/lab3/constraint.yaml
----

== Test constraint


=== Test negative case

In this lab we are going to test how constraint applies to existing resources. For this test we are going to check the starus of the constraint as the existing route's name doesn't fulfil the requirements.

----
oc get requiredroutename.constraints.gatekeeper.sh/required-route-name -o yaml
----

As you can see there is a violation detected for resource "Route" with error message "".

=== Test postive case

As the existing route's name is not valid we are going to redeploy it for a valid format so there will be no violation alert.

----
oc apply -f lab-gatekeeper-files(lab3/petclinic-bluegreen-routename.yaml
----

After waiting the audit interval time there should not be any violation on the constraint.

----
oc get requiredroutename.constraints.gatekeeper.sh/required-route-name -o yaml
----
