= Lab 3 - Required route names
:author: Coral Romero
:email: cromerob@redhat.com
:imagesdir: ./images
:toc: left
:toc-title: Required route name

[Abstract]

In this use case we are going to verify that the route name follows the required pattern to validate it.

For this example we are going to apply this constraint over two different projects, "petclinic-bluegreen-$USER" which is the production environment and "petclinic-beta-$USER" which is the development environment. 

Previously we are going to create a Config resource to exclude "webhook" process from "petclinic-beta-$USER" project so we will be able to create non valid resources but those violations will be registered on the status.

:numbered:
== Deploy constraint

=== Deploy Config

As mentioned we need to create a config resource to exclude some processes from a namespace, "webhook" for "petclinic-beta-$USER". This is a cluster wide resource which should be created by an user with cluster-admin privileges so you can check the existing resource with this command:

----
oc get config.config.gatekeeper.sh/config -o yaml -n openshift-gatekeeper-system
----

=== Deploy Constraint Template

First we need to deploy the constraint templates where we are going to check the existing name of the object under test.

----
oc apply -f lab-gatekeeper-files/lab3/constraintTemplate.yaml
----

=== Deploy Constraint 

Additionally we need to deploy the constraints where we are going to limit the impact to "petclinic-bluegreen-$USER" and "petclinic-beta-$USER"  namespace and specify the required name.

For this example parameters are:

- Namespace where the rule is implemented: petclinic-bluegreen-$USER and petclinic-beta-$USER.
- Resource under test: Route.
- Required name: "route-petclinic-bluegreen".
- Enforcement action: deny.

----
oc process -f lab-gatekeeper-files/lab3/constraint.yaml -p USER=$USER  | oc apply -f -
----

== Test constraint


=== Test negative case

In this lab we are going to test how constraint applies to existing resources. For this test we are going to check the status of the constraint as the existing route's name doesn't fulfil the requirements.

----
oc get requiredroutename.constraints.gatekeeper.sh/required-route-name -o yaml
----

As you can see there is a violation detected for resource "Route" with error message "Route must include string: route-petclinic-bluegreen".

For the second namespace "petclinic-beta-$USER" as webhook process is excluded if we try to deploy the same app we should be allowed but getting the same violation warning, so total violations count will be 2.

----
oc apply -f  lab-gatekeeper-files/lab2/deploy-app-green.yaml -n petclinic-beta-$USER
----

=== Test postive case

As the existing route's name is not valid we are going to redeploy it for a valid format so there will be no violation alert.

----
oc delete all --selector app=quarkus-petclinic-blue -n petclinic-bluegreen-$USER
oc delete all --selector gatekeeper=quarkus-petclinic-green -n petclinic-beta-$USER
oc apply -f lab-gatekeeper-files/lab3/deploy-app-blue.yaml -n petclinic-bluegreen-$USER
----

After waiting the audit interval time there should not be any violation on the constraint.

----
oc get requiredroutename.constraints.gatekeeper.sh/required-route-name -o yaml
----


To finish this lab, delete all the resources:

----
oc delete all --selector app=quarkus-petclinic-blue  -n petclinic-bluegreen-$USER
----
