= Lab 5 - Sync data
:author: Coral Romero
:email: cromerob@redhat.com
:imagesdir: ./images
:toc: left
:toc-title: Sync data


[Abstract]
In this lab we are going to implement a constraint to see how the syncing feature works. 

As explaing at the beginning of this course, syncing feature allows to sync objects in order to be accessible apart from the resource under test.

For this example we want to verify that before deploying any pod there should be a deployed `ResourceQuota` on that `namespace`.


:numbered:
== Deploy constraint

Before deploying any constraint, let's verify again that `Config` resource defines namespaces to be synced.

----
oc get config.config.gatekeeper.sh/config -o yaml -n openshift-gatekeeper-system
----

=== Deploy Constraint Template

First of all we are going to the deploy the constraint template where we are going to define how a namespace should has a deployed `ResourceQuota` for deploying any deployment resource.

Additionally, on this constraint you can see how data inventory is accessed using the syntax we introduced at the beginning:

----
oc apply -f lab-gatekeeper-files/lab5/constraintTemplate.yaml
----

=== Deploy Constraint

Then we have to deploy constraint where we are going to define the parameters:

 - Namespace: `petclinic-bluegreen-$USER`.
 - Resource under test: `Deployment`.
 - Enforcement action: `deny`.

----
oc process -f lab-gatekeeper-files/lab5/constraint.yaml -p USER=$USER  | oc apply -f -
----

== Test constraint

=== Test negative

For testing this constraint, our environment has two namespaces, one with a deployed resource quota resource `petclinic-beta-$USER` and another onw without it.

For testing the negative case we are going to try to deploy an app into a namespace without a resource quota.

----
oc apply -f lab-gatekeeper-files/lab5/deployment-app-blue.yaml -n petclinic-bluegreen-$USER
----

As there is no resource quota, you should see error message `The Pod could not be created because the petclinic-bluegreen-$USER namespace doesn't contain any ResourceQuota object`.

=== Test positive

For testing the positive case we are going to deploy an app into a namespace with a `ResourceQuota`. As this deployment follows the existing constraint there shouldn't be any issue.

----
oc apply -f lab-gatekeeper-files/lab5/deployment-app-blue.yaml -n petclinic-beta-$USER
----


