apiVersion: constraints.gatekeeper.sh/v1beta1
kind: MaxReplicas
metadata:
  name: maxreplicas
spec:
  enforcementAction: deny      
  match:
    namespaces:
      - "petclinic-bluegreen-user0"      
    kinds:
      - apiGroups: ["*"]
        kinds: ["Deployment"]
  parameters:
    replicas: 3

